---
vyos1:
  :networks:
    net1: "10.0.1.11"
    net2: "10.0.2.11"
vyos2:
  :networks:
    net1: "10.0.1.12"
    net3: "10.0.3.11"
vyos3:
  :networks:
    net2: "10.0.2.13"
vyos4:
  :networks:
    net3: "10.0.3.14"
